### PR TITLE
Replace the deprecated include with include_task

### PR DESCRIPTION
**Pull request by geoffr**
This will fix the Deprecation warning: "ansible.builtin.include has been removed"

Currently Ansible runs are breaking with:

```ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.```

### CODE REVIEW

**Comment by npmdnl** [comment]
@geoffr please rebase

**Comment by geoffr** [comment]
> @geoffr please rebase

I have done so.

Thanks
Geoff

**Comment by npmdnl** [comment]
> > @geoffr please rebase
> 
> I have done so.
> 
> Thanks Geoff

I'm still seeing just one commit.

**Review by npmdnl — COMMENTED** [review]
LGTM

**Pull request merged**
