### PR TITLE
added 4.6.x and 4.7.x release train repositories

### PR DESCRIPTION
**Pull request by ZaphodB**
just what is says on the subject
Successfully tested for pdns_rec_powerdns_repo_47 on Ubuntu 20.04.4 LTS.

### CODE REVIEW

**Review by rkerr — COMMENTED** [review]
Looks good to me - might also want to alter the github workflow file to add scenarios for 4.6/4.7?

**Comment by ZaphodB** [comment]
It looks like the github workflow would involve adding to molecule as well which i don't know my way around.
In particular i'm confused as to why the 44 test has
`assert f.contains('User=')`
while 45 tests for
`assert not f.contains('User=')`
so i would rather leave this to someone in the know.

**Comment by Habbie** [comment]
`vars/main.yml` adds User= and Group= for 4.3 and below (not 4.4 and below) so I'm not sure! Also the tests are entirely broken right now..

**Comment by Habbie** [comment]
I fixed the tests!

**Comment by npmdnl** [comment]
This closes #76

**Pull request merged**
