### PR TITLE
Role refactoring to address #11

### PR DESCRIPTION
**Pull request by atosatto**
This PR contains some breaking changes to attempt fix PR #11.
- Removed the url installation method (in case, we still need a commit to remove it from the doc)
- Added actions to query the APT/YUM repositories to get the available `pdns_recursor` package version
- Configuring the `pdns_recursor` before actually installing it

Off course, this is open for discussion.

### CODE REVIEW

**Comment by atosatto** [comment]
Well, as discussed on IRC with @pieterlexis and @Habbie, I've replace the `awk` plus shell trick to obtain the available `pdns-recursor` package list from the remote repos with dedicate modules miming the `apt-cache madison` command.

**Comment by atosatto** [comment]
@Habbie and @pieterlexis this PR is now completed.
It's a lot of stuff but I really would like to hear some feedbacks from you (and hopefully get you merge it).

**Comment by atosatto** [comment]
To test all the stuff (if you have Vagrant and Virtualbox installed) and see how it does work:

```
$ pip install molecule
# Get the available test platforms
$ molecule list
AVAILABLE PLATFORMS
centos-7       (default)
ubuntu-xenial
debian-jessie
# eg test on ubuntu-xenial with
molecule converge --platform=ubuntu-xenial
```

The executed playbook is `playbook.yml` in the project root directory.

**Comment by pieterlexis** [comment]
:+1: lgtm!

**Pull request merged**
